language: python

python:
  - 3.6
  - 2.7

sudo: false

# command to install dependencies
install:
  - pip install -r requirements.txt

script:
    - python -m PVGeo test

notifications:
  email:
    recipients:
      - info@pvgeo.org
    on_success: never # default: change
    on_failure: always # default: always
