sudo: required

dist: xenial

os:
  - linux

language: python

python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'

env:
  global:
    # Doctr deploy key for OpenGeoVis/PVGeo
    - secure: "UFohcAvj8rOpYEYt1pItOKx7yem561t/Ks31qJMd5JUitNPnGwHy06YqSFJ4qEsk/6DKc/gFU2nTxDQm+2y0HWL8m/WGa5sxSLe0iIYdrc4IyeRvMUIGyTD3y+ZFcO+YXoPRSiK4uufTb0Nh8CqoDzL2bSqy4lljVgTu0Q3wVBEDakH63fFC6bp7ztykyyE+vQ4AjEIUAvCPhgZOvjrDwZDmwVB3HeLoroTbXLitCYfBiEswxxuoClIIWebCNaBmVUXTAIzVxv31uzbTvFduqjRtS5110Jx1SYOrct/K4oJKAafRvnxaPffLPQcvzJckW0NsgROxop62bA+tnTyREfXqoUBnY7KGcaqfAxTz/yBSoQn8VGB20S4nh2OB0vf7QF/kEB0mDETvVlUQUTjCfnPFUxR9QbrB9jexO4OaEy7LuHSnaN0x4Tq8od9mopXpWZXKVVAVNq6+oo1c31SPAHy5QrhTCTX7QuXsA0oJ8rv/RaDGTe9L4PozRt81nEr1ZlwZOfvYny+4ZMlpgHz4evqDyE4JBMaXaNhWBkuve7FaQKjBKCU/bG0arPUE7/N+0h0GgEG6QUhLrI6TC05fj/AN/q1J5zijqhExIFwH8MbiY0ukNdUyaYBGQMlo86PB/0EG2kojgtuLNXAJX6+ZBIkKpcJdtoRV+kQfG8SJ/Yg="

before_install:
  # configure a headless display
  - git clone --depth 1 git://github.com/pyvista/gl-ci-helpers.git
  - source ./gl-ci-helpers/travis/setup_headless_display.sh

install:
    - pip install -r requirements.txt
    - if [[($TRAVIS_PYTHON_VERSION == 3.7)]]; then
        pip install -r ./docs/requirements.txt;
      fi
    - python setup.py install

script:
    - coverage run tests/__main__.py
    - codecov --token=8da9d332-1618-450d-8654-09a8ecf3c2dc
    - python tests/__main__.py close # exit with error code if problem occurs
    # Make docs - I have no idea why but it always segfault on first make - so make twice
    - if [[($TRAVIS_PYTHON_VERSION == 3.7)]]; then
        echo "Building and uploading the docs";
        cd ./docs;
        make html;
        set -e;
        make html;
        cd ..;
      fi

notifications:
    slack:
        on_success: change
        on_failure: change
        rooms:
            - pvgeo:m3aUlu4IVCCVrPnbTuX1C3J5#development
    email:
        recipients:
            - info@pvgeo.org
        on_success: never
        on_failure: never

deploy:
  - provider: script
    script: sh ./docs/deploy_docs_from_travis.sh
    skip_cleanup: true
    on:
      condition: ($TRAVIS_PYTHON_VERSION == 3.7) && ($TRAVIS_REPO_SLUG == 'OpenGeoVis/PVGeo') && ($TRAVIS_BRANCH == 'master') && ($DOCS_TRIGGER == 'BANE_RULES')
  - provider: pypi
    user: "pvgeosupport"
    password:
        secure: L3eSpvBG9sJeGpUCybkisOdpjIv3BxEy2BPHDimSrJE26UnJ4my/8Xq05GWejH4IOBhyo6ZmlKy2olZeTaIY+0+kf2zpR8C0b5DW4B2mXKkiEm7JpVdWmlc/Kcw7aBOvn3APH5K52if58p3M65P+9nkKE91FdmZUQP41e32lHl6yYMo8PBU8x7imMdL4Myl5J+5DxtYnr4tC07Td4KTvhNJyUM0Y5i3Qyp1AELlB36M6gcvUnRCAKqQDq5phtufrQHM/TjAeyuX2RwzDtZhILWEYHYPDZ0m8emPV5OYbklqHaEM5DcY4Vd50l/yw22mm154nqsOUr3nz2URLV5u3qea+5WZeQRaDjFNVHe0udO8axhT8I2VPyatnCX2q9GmDCF77Dl9Fv/ZLXP80qanL1BfwjPIB1vkMPR+6y0n8DcI3MM5SMZYm80igPLY/AMqBFsWoU9Fsp+luvx6Dcmf3s7RTKf0tqOJcog07GRzK0c4up8uZwBir3rjQzhv4y0DT3IfillQB7SmMzH4xW0vpi/txvaBNvlI0OT3eIiygH79FoxzWZO0YdzZLV33ZUU7nKk+TsQka4LmjksVQw2+aK5fVoJ9VuUVYYfZDtoJICKfktfv7UFdl0tJkjHArSOrPVmsrit54uESmKsMIMzeQi+fY/Baz63utkXFm+8U6D3k=
    on:
        repo: OpenGeoVis/PVGeo
        branch: master
        tags: true
        python: 2.7 # Only deploy from python 2 as more likely to prevent broken builds
